### ISSUE TITLE
How to customize other aspects of the panel?

### ISSUE THREAD

**Issue by ferozed** [VagnerDomingues/docsify-example-panels#21]
I am trying to customize the panel so that it has a border, like so:

```
  <style>
    :root{
    
        /* Standards */
        --docsify-example-panels-border: solid;
    }
  </style>
```

But this does not customize the border. I suspect it is because there is a whitelist of CSS attributes that are rendered to the page?

is that correct?

is there any way to achieve what I want?

Sorry if this is a newbie question. I am new to CSS.

**Comment by VagnerDomingues** [comment]
sorry for the late answer.

so, the height of the panel is adjusted by it's contents, so it was intended not to have borders, because it won't ever fit in grid or table styles.

what I suggest you can do is create a container inside the panel and customized it with your custom css rules

but if you still want to add borders to it you can do by adding:

```
.docsify-example-panel.right-panel, .docsify-example-panel.left-panel  {
    border: 1px solid green;
}
```
to your stylesheets.
